Funcy-ICT/Funcy_Portfolio_Backend

app/interfaces/server.go, app/packages/utils/auth/jwt.go, app/usecase/auth.go, cmd/main.go
=> [fix]import順を修正

swagger/swagger.yaml
=> [fix]swagger.yaml

app/domain/entity/work.go, app/domain/repository/work_repository.go, app/infrastructure/work.go, app/interfaces/handler/work.go, app/interfaces/response/work.go, app/interfaces/server.go, app/usecase/work.go
issue #27
- `entity.ReadWorksList` に `Description` フィールドがなかったため、追加しました
- {number} に想定外の値が入っていたとき `400` を返すようにしました
- 0 < {number} <= 4294967295 (uint の上限)
=> [add] 作品一覧取得機能の実装

docker-compose.yml, swagger/swagger.yaml
[swagger](http://localhost:8002)を開いてページ上部のserversで8003を選択することでmockを使用できるようにしました。
=> [fix]swagger.yml内の表記揺れを修正

app/domain/repository/work_repository.go, app/infrastructure/work.go, app/interfaces/handler/work.go, app/interfaces/response/error.go, app/interfaces/server.go, app/usecase/work.go
issue #32 
sql で `Delete`文を実行したとき、削除対象が存在していない場合でもエラーが出ないため、事前に`Select`で存在を確認してから削除するようにしました
=> [add] 作品削除機能の実装

Dockerfile, Makefile, README.md, cmd/main.go, docker-compose.yml, go.mod
migrate後にホットリロードをかませないとエラーが返される不具合を修正とreadmeの修正
=> migrate後に発生するエラーの修正

Makefile, README.md, swagger/swagger.yaml
swagger : APIに関する情報を最新版にアップデート
readme : 検証環境立ち上げ方法の追記
=> [fix]ドキュメントの修正

README.md, docker-compose.yml
ローカルでメール関連機能を検証するためにmailhogを導入しました
以下がイシューです
[issue](https://github.com/Funcy-ICT/Funcy_Portfolio_Backend/issues/46)
メール確認用のUIが立ち上がっている
=> [feat]mailhog環境の構築

app/domain/entity/work.go, app/domain/repository/work_repository.go, app/infrastructure/work.go, app/interfaces/handler/work.go, app/interfaces/request/work.go, app/interfaces/server.go, app/usecase/work.go
https://github.com/Funcy-ICT/Funcy_Portfolio_Backend/issues/34
エンドポイント`/work/{workID}` を実装し、作品情報の更新の機能を追加しました。
- レスポンスが想定通りか
- 記法
=>  [feature]作品情報更新APIの実装

app/domain/entity/work.go, app/domain/repository/work_repository.go, app/infrastructure/work.go, app/interfaces/handler/work.go, app/interfaces/request/work.go, app/interfaces/response/work.go, app/interfaces/server.go, app/usecase/work.go, db/migration/sql/20230508084652_alter_work_thumbnail.up.sql, go.mod, go.sum
Reverts Funcy-ICT/Funcy_Portfolio_Backend#57
作品一覧を取得できなくなってしまったため原因調査のためリバート
=> Revert "[feature] #33 サムネイル画像用のカラムを追加"

Dockerfile, Makefile, README.md, app/domain/entity/work.go, app/domain/repository/work_repository.go, app/infrastructure/work.go, app/interfaces/handler/work.go, app/interfaces/request/work.go, app/interfaces/response/work.go, app/interfaces/server.go, app/usecase/work.go, db/migration/sql/20230508084652_alter_work_thumbnail.up.sql, go.mod, swagger/swagger.yaml
Reverts Funcy-ICT/Funcy_Portfolio_Backend#68
=> Revert "[fix]61の差分を取り込み"

app/domain/entity/work.go, app/interfaces/handler/work.go, app/usecase/work.go
https://github.com/Funcy-ICT/Funcy_Portfolio_Backend/issues/59
作品情報新規作成APIに関するドメイン層の関数のうち、UUID付与に関わる機能をusecase層に移す
- レスポンスが想定通りか
- 書き方が作品情報更新APIと同様になっているか
=> [fix] #59 作品情報新規作成APIに関するドメイン層の関数のレイヤー変更

app/domain/entity/work.go, app/infrastructure/work.go, app/interfaces/handler/work.go, app/interfaces/request/work.go, app/interfaces/response/work.go, app/usecase/work.go, swagger/swagger.yaml
Reverts Funcy-ICT/Funcy_Portfolio_Backend#75
=> Revert "Fix/61/swagger works"

app/interfaces/server.go, file-server/config/config.go, file-server/pkg/controller/file.go, swagger/swagger.yaml
- フロント側でCookieを扱えるようにcorsの設定を修正
- ファイルサーバのport番号を修正
- swaggerの修正
=> [bug]corsの設定ミスを修正

db/migration/sql/20230508084652_alter_work_thumbnail.up.sql
https://github.com/Funcy-ICT/Funcy_Portfolio_Backend/issues/92
thumnailの長さを128に変更
ファイルサーバーが返したURLを保存できた
- 2edf5d76-06c5-4308-9267-d22488e1c684スクリーンショット 2023-07-13 18.34.48.png
なし
=> [fix] thumnailの文字列サイズを修正

app/interfaces/middleware/auth.go
https://github.com/Funcy-ICT/Funcy_Portfolio_Backend/issues/94
bearer cookieで認証が通ること
bearer
cookie
=> [bug]bearer toeknの認証を通すように修正

app/interfaces/handler/auth.go, app/interfaces/response/auth.go, app/usecase/auth.go, swagger/swagger.yaml
- ログイン時にuserIDを返却する
https://github.com/Funcy-ICT/Funcy_Portfolio_Backend/issues/97
- レスポンスにuserIDを含める
- swaggerを更新
responseにuserIDが含まれている
web login
mlogin
=> [fix]ログイン時にuserIDを返却する

app/domain/repository/auth_repository.go, app/infrastructure/auth.go, app/interfaces/handler/auth.go, app/interfaces/server.go, app/usecase/auth.go, swagger/swagger.yaml
- ワンタイムパスワードによる認証時にCookieをセットする
- エンドポイント名を変更
- auth/code → authcode 
https://github.com/Funcy-ICT/Funcy_Portfolio_Backend/issues/99
- cookieにtokenをセット
- 
cookieにtokenが含まれていること
=> [fix]cookieをセットするように修正

app/domain/entity/work.go, app/infrastructure/work.go, app/interfaces/handler/work.go, app/usecase/work.go, swagger/swagger.yaml
=> [fix] work作成・更新APIの依存関係の見直し

app/infrastructure/work.go
#137 
非公開作品を取得しないようにする
1. 作品投稿の本人でもhomeにworkを出力しないでいいか
2. セキュリティどこまで追うか(work_idをもとにwork情報を取得するときには本人か確認するか)
=> [fix] 非公開の作品を取得しない
